/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dflow4k.app

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = MessageUtils.getMessage()
    val result = tokens.take(1)
    println(WordUtils.capitalize(result))
}
